/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M20
 * Generated at: 2017-05-15 11:36:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.roomspage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rooms_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>SOBE</title>\n");
      out.write(" <!-- Latest compiled and minified CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- jQuery library -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Latest compiled JavaScript -->\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"roomsstyle.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar navbar-default\" id=\"navbar-override\" role=\"navigation\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("\t\t    <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t    <div class=\"navbar-header\">\n");
      out.write("\t\t      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-brand-centered\">\n");
      out.write("\t\t        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\n");
      out.write("\t\t      </button>\n");
      out.write("\t\t      <div class=\"navbar-brand navbar-brand-centered\">HOTEL MOTEL</div>\n");
      out.write("\t\t    </div>\n");
      out.write("\n");
      out.write("\t\t    <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("\t\t    <div class=\"collapse navbar-collapse\" id=\"navbar-brand-centered\">\n");
      out.write("\t\t      <ul class=\"nav navbar-nav\">\n");
      out.write("\t\t        <li><a href=\"../reservationspage/reservation.jsp\">REZERVACIJE</a></li>\n");
      out.write("\t\t        <li><a href=\"../pricespage/prices.jsp\">CENOVNIK</a></li>\n");
      out.write("\t\t        <li><a href=\"../roomspage/rooms.jsp\">TIP SOBA</a></li>\n");
      out.write("\t\t      </ul>\n");
      out.write("\t\t      <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t        <li><a href=\"../aboutpage/aboutus.jsp\">O NAMA</a></li>\n");
      out.write("\t\t        <li><a href=\"../kontaktpage/kontakt.jsp\">KONTAKT</a></li>\n");
      out.write("\t\t        <li><a href=\"#\">SIGN OUT</a></li>\t\t        \n");
      out.write("\t\t      </ul>\n");
      out.write("\t\t    </div><!-- /.navbar-collapse -->\n");
      out.write("\t\t  </div><!-- /.container-fluid -->\n");
      out.write("</nav>\n");
      out.write("<div class=\"carousel fade-carousel slide\" data-ride=\"carousel\" data-interval=\"4000\" id=\"bs-carousel\">\n");
      out.write("  \n");
      out.write("\n");
      out.write("  <!-- Indicators -->\n");
      out.write("  <ol class=\"carousel-indicators\">\n");
      out.write("    <li data-target=\"#bs-carousel\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("    <li data-target=\"#bs-carousel\" data-slide-to=\"1\"></li>\n");
      out.write("    <li data-target=\"#bs-carousel\" data-slide-to=\"2\"></li>\n");
      out.write("  </ol>\n");
      out.write("  \n");
      out.write("  <!-- Wrapper for slides -->\n");
      out.write("  <div class=\"carousel-inner\">\n");
      out.write("    <div class=\"item slides active\">\n");
      out.write("    <!-- Overlay -->\n");
      out.write("  <div class=\"overlay\"></div>\n");
      out.write("      <div class=\"slide-1\"></div>\n");
      out.write("      <div class=\"hero\">\n");
      out.write("        <hgroup>\n");
      out.write("            <h1>JEDNOKREVETNE</h1>        \n");
      out.write("            <h3>King ili Queen size</h3>\n");
      out.write("        </hgroup>\n");
      out.write("        <a href=\"../reservationspage/reservation.jsp\"><button class=\"btn btn-hero btn-lg\" role=\"button\">Rezervisite odmah</button></a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"item slides\">\n");
      out.write("      <div class=\"slide-2\"></div>\n");
      out.write("      <div class=\"hero\">        \n");
      out.write("        <hgroup>\n");
      out.write("            <h1>DVOKREVETNE</h1>        \n");
      out.write("            <h3>Najbolje za vas i porodicu</h3>\n");
      out.write("        </hgroup>       \n");
      out.write("        <button class=\"btn btn-hero btn-lg\" role=\"button\">Rezervisite odmah</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"item slides\">\n");
      out.write("      <div class=\"slide-3\"></div>\n");
      out.write("      <div class=\"hero\">        \n");
      out.write("        <hgroup>\n");
      out.write("            <h1>TROKREVETNE</h1>        \n");
      out.write("            <h3>Najbolje za vas i porodicu</h3>\n");
      out.write("        </hgroup>\n");
      out.write("        <button class=\"btn btn-hero btn-lg\" role=\"button\">Rezervisite odmah</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div> \n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
