/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M20
 * Generated at: 2017-05-25 10:56:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.indexpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>HOTEL MOTEL</title>\n");
      out.write(" <!-- Latest compiled and minified CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- jQuery library -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Latest compiled JavaScript -->\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("<script src=\"indexscript.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"indexstyle.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar navbar-default\" id=\"navbar-override\" role=\"navigation\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("\t\t    <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t    <div class=\"navbar-header\">\n");
      out.write("\t\t      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-brand-centered\">\n");
      out.write("\t\t        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\n");
      out.write("\t\t      </button>\n");
      out.write("\t\t      <div class=\"navbar-brand navbar-brand-centered\">HOTEL MOTEL</div>\n");
      out.write("\t\t    </div>\n");
      out.write("\n");
      out.write("\t\t    <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("\t\t    <div class=\"collapse navbar-collapse\" id=\"navbar-brand-centered\">\n");
      out.write("\t\t      <ul class=\"nav navbar-nav\">\n");
      out.write("\t\t        <li><a href=\"webapp/CenovnikServlet\">REZERVACIJE</a></li>\n");
      out.write("\t\t        <li><a href=\"../pricespage/prices.jsp\">CENOVNIK</a></li>\n");
      out.write("\t\t        <li><a href=\"../roomspage/rooms.jsp\">TIP SOBA</a></li>\n");
      out.write("\t\t      </ul>\n");
      out.write("\t\t      <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t        <li><a href=\"../aboutpage/aboutus.jsp\">O NAMA</a></li>\n");
      out.write("\t\t        <li><a href=\"../kontaktpage/kontakt.jsp\">KONTAKT</a></li>\n");
      out.write("\t\t        <li><a href=\"#\">SIGN OUT</a></li>\t\t        \n");
      out.write("\t\t      </ul>\n");
      out.write("\t\t    </div><!-- /.navbar-collapse -->\n");
      out.write("\t\t  </div><!-- /.container-fluid -->\n");
      out.write("</nav>\n");
      out.write("<div id=\"bootstrap-touch-slider\" class=\"carousel bs-slider slide  control-round indicators-line\" data-ride=\"carousel\" data-pause=\"hover\" data-interval=\"5000\" >\n");
      out.write("\n");
      out.write("            <!-- Indicators -->\n");
      out.write("            <ol class=\"carousel-indicators\">\n");
      out.write("                <li data-target=\"#bootstrap-touch-slider\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                <li data-target=\"#bootstrap-touch-slider\" data-slide-to=\"1\"></li>\n");
      out.write("                <li data-target=\"#bootstrap-touch-slider\" data-slide-to=\"2\"></li>\n");
      out.write("            </ol>\n");
      out.write("\n");
      out.write("            <!-- Wrapper For Slides -->\n");
      out.write("            <div class=\"carousel-inner\" role=\"listbox\">\n");
      out.write("\n");
      out.write("                <!-- Third Slide -->\n");
      out.write("                <div class=\"item active\">\n");
      out.write("\n");
      out.write("                    <!-- Slide Background -->\n");
      out.write("                    <img src=\"https://images.trvl-media.com/hotels/4000000/3490000/3484400/3484306/3484306_78_z.jpg\" alt=\"Bootstrap Touch Slider\"  class=\"slide-image\"/>\n");
      out.write("                    <div class=\"bs-slider-overlay\"></div>\n");
      out.write("\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <!-- Slide Text Layer -->\n");
      out.write("                            <div class=\"slide-text slide_style_left\">\n");
      out.write("                                <h1 data-animation=\"animated zoomInRight\">Hotel Motel</h1>\n");
      out.write("                                <p data-animation=\"animated fadeInLeft\">Ekskluzivni hotel, Novi Sad</p>\n");
      out.write("                                <a href=\"../pricesspage/prices.jsp\" target=\"_blank\" class=\"btn btn-default\" data-animation=\"animated fadeInLeft\">cenovnik</a>\n");
      out.write("                                <a href=\"../reservationspage/reservation.jsp\" target=\"_blank\"  class=\"btn btn-primary\" data-animation=\"animated fadeInRight\">rezervacije</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- End of Slide -->\n");
      out.write("\n");
      out.write("                <!-- Second Slide -->\n");
      out.write("                <div class=\"item\">\n");
      out.write("\n");
      out.write("                    <!-- Slide Background -->\n");
      out.write("                    <img src=\"http://fridayoffbeat.com/Friday%20Offbeat%20_%20Home_files/restaurant_table_interior_modern_style_39288_1920x1080.jpg\" alt=\"Bootstrap Touch Slider\"  class=\"slide-image\"/>\n");
      out.write("                    <div class=\"bs-slider-overlay\"></div>\n");
      out.write("                    <!-- Slide Text Layer -->\n");
      out.write("                    <div class=\"slide-text slide_style_center\">\n");
      out.write("                        <h1 data-animation=\"animated flipInX\">Pogledajte nasu ponudu prenocista</h1>\n");
      out.write("                        <p data-animation=\"animated lightSpeedIn\">Moderno opremljene sobe lol</p>\n");
      out.write("                        <a href=\"../roomspage/rooms.jsp\" target=\"_blank\" class=\"btn btn-default\" data-animation=\"animated fadeInUp\">sobe</a>\n");
      out.write("                        <a href=\"../reservationspage/reservation.jsp\" target=\"_blank\"  class=\"btn btn-primary\" data-animation=\"animated fadeInDown\">rezervacije</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- End of Slide -->\n");
      out.write("\n");
      out.write("                <!-- Third Slide -->\n");
      out.write("                <div class=\"item\">\n");
      out.write("\n");
      out.write("                    <!-- Slide Background -->\n");
      out.write("                    <img src=\"http://renatures.com/wp-content/uploads/2017/03/beaches-sea-gazebo-palms-chairs-beach-pool-hotel-tropical-hd-wallpaper-android.jpeg\" alt=\"Bootstrap Touch Slider\"  class=\"slide-image\"/>\n");
      out.write("                    <div class=\"bs-slider-overlay\"></div>\n");
      out.write("                    <!-- Slide Text Layer -->\n");
      out.write("                    <div class=\"slide-text slide_style_right\">\n");
      out.write("                        <h1 data-animation=\"animated zoomInLeft\">Hotel Motel</h1>\n");
      out.write("                        <p data-animation=\"animated fadeInRight\">Ekskluzivni hotel, Novi Sad</p>\n");
      out.write("                        <a href=\"../aboutpage/aboutus.jsp\" target=\"_blank\" class=\"btn btn-default\" data-animation=\"animated fadeInLeft\">o nama</a>\n");
      out.write("                        <a href=\"../kontaktpage/kontakt.jsp\" target=\"_blank\" class=\"btn btn-primary\" data-animation=\"animated fadeInRight\">kontakt</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- End of Slide -->\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div><!-- End of Wrapper For Slides -->\n");
      out.write("\n");
      out.write("            <!-- Left Control -->\n");
      out.write("            <a class=\"left carousel-control\" href=\"#bootstrap-touch-slider\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                <span class=\"fa fa-angle-left\" aria-hidden=\"true\"></span>\n");
      out.write("                <span class=\"sr-only\">Previous</span>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <!-- Right Control -->\n");
      out.write("            <a class=\"right carousel-control\" href=\"#bootstrap-touch-slider\" role=\"button\" data-slide=\"next\">\n");
      out.write("                <span class=\"fa fa-angle-right\" aria-hidden=\"true\"></span>\n");
      out.write("                <span class=\"sr-only\">Next</span>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("</div> <!-- End  bootstrap-touch-slider Slider -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
